name: build database

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    paths:
      - database/**

permissions:
  packages: write

jobs:
  push:
    name: "database:${{ matrix.database }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database:
          - chroma
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./database/${{ matrix.database }}
          file: ./database/${{ matrix.database }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/minelat/pterodactyl-images:database_${{ matrix.database }}
